name: Build and deploy WebAPI .Net Framework 4.8 on self host

on:
  push:
    branches: main
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build

    - name: Restore Packages
      run: nuget restore WebAPI.sln

    - name: Build UnitTest
      run: |
        msbuild.exe WebAPI.UnitTest\WebAPI.UnitTest.csproj /p:configuration="Release"

    - name: Run vstests
      uses: microsoft/vstest-action@v1.0.0
      with:
        testAssembly: WebAPI.UnitTest.dll
        searchFolder: .\WebAPI.UnitTest\bin\Release\
        runInParallel: true

    - name: Build Solution
      run: |
        msbuild.exe WebAPI.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: WebAPI
        path: "./_build"

  deploy:
    needs: build
    runs-on: self-hosted
    env:
      app_name: 'webapi'
      app_pool_name: 'webapi-pool'
      physical_path: 'D:\deployments\WebAPI'
      IIS_WEBSITE_NAME: 'Default Web Site'
      IIS_SERVER_COMPUTER_NAME: 'localhost'
      IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
      app_pool_user_service: 'webapi'
      app_pool_password_service: 'Test1Testing'
      source_physical_path: 'D:\deployments\'
    environment:
      name: Test

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ env.physical_path }}

    - name: Change directory
      run: |
        cd "C:\Program Files\IIS\Microsoft Web Deploy V3\"

    - name: Deploy WebAPI with MSDeploy
      run: |
        ./msdeploy -verb:sync -source:iisApp=`"${{ env.physical_path }}\WebAPI`" -dest:iisApp=`"Default Web Site\webapi`" -enableRule:DoNotDeleteRule